package com.mk.RecipeApplication.instruction;

import javax.persistence.*;

/**
 * Represents an instruction used in a recipe. A recipe has multiple instructions to prepare.
 * This entity maps to the instructions table of the database.
 */
@Entity
@Table(name="instructions")
public class Instruction {

    /**
     * Unique identifier for the instruction.
     * Auto-generated by a sequence of the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "instructions_id_seq")
    @SequenceGenerator(name = "instructions_id_seq", sequenceName = "instructions_id_seq", allocationSize = 1)
    private int id;

    /**
     * Id of the recipe this instruction belongs to.
     */
    private int recipeId;

    /**
     * Step number of the instruction, when preparing the recipe.
     */
    private int step;

    /**
     * Description what to do in this instruction section.
     */
    private String description;

    /**
     * Full constructor to initialize all fields.
     *
     * @param id unique identifier for the instruction
     * @param recipeId ID of the recipe this instruction belongs to
     * @param step Step number of the instruction
     * @param description Description what to do in the instruction
     */
    public Instruction(int id, int recipeId, int step, String description) {
        this.id = id;
        this.recipeId = recipeId;
        this.step = step;
        this.description = description;
    }

    /**
     * Contructor without id for creating new instructions.
     *
     * @param recipeId ID of the recipe this instruction belongs to
     * @param step Step number of the instruction
     * @param description Description what to do in the instruction
     */
    public Instruction(int recipeId, int step, String description) {
        this.recipeId = recipeId;
        this.step = step;
        this.description = description;
    }

    /**
     * Default contructor required for JPA
     */
    public Instruction() {}

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getRecipeId() {
        return recipeId;
    }

    public void setRecipeId(int recipeId) {
        this.recipeId = recipeId;
    }

    public int getStep() {
        return step;
    }

    public void setStep(int step) {
        this.step = step;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }
}
